// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import TypewriterController from "./typewriter_controller"
application.register("typewriter", TypewriterController)
